name: PaperAccurateBlockPlacement
version: 1.2.0
main: net.dungeondev.accurateblockplacement.AccurateBlockPlacement
description: Implements the Carpet AccurateBlockPlacement protocol on Paper
author: hxrry27 (forked from DungeonDev)
api-version: '1.21'
dependencies:
  server:
    packetevents:
      required: true

commands:
  abp:
    description: PaperAcurateBlockPlacement commands
    usage: /abp [reload]

permissions:
  accurateblockplacement.reload:
    description: Allows reloading the plugin config
    default: op